services:
  portfolio:
    build: .
    container_name: portfolio
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro 